//
//  FishOnViewController.m
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import "FishOnViewController.h"
#import "SettingsViewController.h"
#import "NewRouteViewController.h"
#import "HomeViewController.h"

#import "GradientView.h"
#import "MKMapView+ZoomLevel.h"

@implementation FishOnViewController


- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
    return UIInterfaceOrientationIsPortrait(toInterfaceOrientation);
}

- (void)viewDidLoad {
  [super viewDidLoad];
  
  // ----------------------------;
  // View Controller Root View;
  // ----------------------------;
  
  UIView *contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 460)];
  contentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  
  // ----------------------------;
  // UINavigationBar -> navigationBar1;
  // ----------------------------;
  
  UINavigationBar *navigationBar1 = [[UINavigationBar alloc] initWithFrame:CGRectMake(0, 0, 320, 44)];
  navigationBar1.delegate = (id<UINavigationBarDelegate>)self;
  UINavigationItem *navigationBar1BackItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  UINavigationItem *navigationBar1TopItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  NSArray *navigationBar1Items = [NSArray arrayWithObjects:navigationBar1BackItem, navigationBar1TopItem, nil];
  [navigationBar1 setItems:navigationBar1Items animated:NO];
  [contentView addSubview:navigationBar1];
  navigationBar1.alpha = 1.0;
  navigationBar1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
  navigationBar1.barStyle = UIBarStyleBlack;
  navigationBar1.tintColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  navigationBar1.translucent = YES;
  navigationBar1.topItem.title = @"Scout";
  [navigationBar1 setTitleVerticalPositionAdjustment:0.0 forBarMetrics:UIBarMetricsDefault];
  navigationBar1.topItem.hidesBackButton = YES;
  [navigationBar1 release];
  
  
  // ----------------------------;
  // UIButton -> imageButton1;
  // ----------------------------;
  
  UIButton *imageButton1 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton1.frame = CGRectMake(276, 0, 44, 44);
  [contentView addSubview:imageButton1];
  imageButton1.alpha = 1.0;
  imageButton1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton1 setTitle:@"" forState:UIControlStateNormal];
  [imageButton1 setImage:[UIImage imageNamed:@"FishOnViewController_Image_1.png"] forState:UIControlStateNormal];
  imageButton1.enabled = YES;
  [imageButton1 setTitleColor:[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0] forState:UIControlStateNormal];
  [imageButton1 addTarget:self action:@selector(didTap_imageButton1:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // MKMapView -> mapView1;
  // ----------------------------;
  
  MKMapView *mapView1 = [[MKMapView alloc] initWithFrame:CGRectMake(0, 44, 320, 367)];
  [contentView addSubview:mapView1];
  mapView1.alpha = 1.0;
  mapView1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  mapView1.mapType = MKMapTypeHybrid;
  [mapView1 setCenterCoordinate:CLLocationCoordinate2DMake(37.33181999999998, -122.03117999999999) zoomLevel:6 animated:NO];
  [mapView1 release];
  
  
  // ----------------------------;
  // MockTextureView -> textureView1;
  // ----------------------------;
  
  UIView *textureView1 = [[UIView alloc] initWithFrame:CGRectMake(0, 162, 320, 303)];
  UIView *textureView1ContentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 303)];
  textureView1ContentView.clipsToBounds = YES;
  textureView1ContentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  [textureView1 addSubview:textureView1ContentView];
  [textureView1ContentView release];
  [contentView addSubview:textureView1];
  textureView1.alpha = 1.0;
  textureView1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textureView1.backgroundColor = [UIColor colorWithPatternImage:[UIImage imageNamed:@"FishOnViewController_Image_2.png"]];
  textureView1.layer.cornerRadius = 0.0;
  textureView1.layer.borderWidth = 0.0;
  textureView1.layer.borderColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0].CGColor;
  textureView1.layer.shadowColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0].CGColor;
  textureView1.layer.shadowOpacity = 0.0;
  textureView1.layer.shadowRadius = 3.0;
  textureView1ContentView.layer.cornerRadius = 0.0;
  textureView1.layer.shadowOffset = CGSizeMake(0, -3);
  [textureView1 release];
  
  
  // ----------------------------;
  // UIButton -> imageButton2;
  // ----------------------------;
  
  UIButton *imageButton2 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton2.frame = CGRectMake(276, 0, 44, 44);
  [textureView1ContentView addSubview:imageButton2];
  imageButton2.alpha = 1.0;
  imageButton2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton2 setTitle:@"" forState:UIControlStateNormal];
  [imageButton2 setImage:[UIImage imageNamed:@"FishOnViewController_Image_3.png"] forState:UIControlStateNormal];
  imageButton2.enabled = YES;
  [imageButton2 setTitleColor:[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0] forState:UIControlStateNormal];
  [imageButton2 addTarget:self action:@selector(didTap_imageButton2:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> roundedRectButton3;
  // ----------------------------;
  
  UIButton *roundedRectButton3 = [UIButton buttonWithType:UIButtonTypeRoundedRect];
  roundedRectButton3.frame = CGRectMake(163, 240, 147, 50);
  [textureView1ContentView addSubview:roundedRectButton3];
  roundedRectButton3.alpha = 1.0;
  roundedRectButton3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [roundedRectButton3 setTitle:@"Stop Route" forState:UIControlStateNormal];
  [roundedRectButton3 setTitleColor:[UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0] forState:UIControlStateNormal];
  roundedRectButton3.titleLabel.font = [UIFont fontWithName:@".HelveticaNeueUI-Bold" size:15.0];
  [roundedRectButton3 addTarget:self action:@selector(didTap_roundedRectButton3:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> roundedRectButton4;
  // ----------------------------;
  
  UIButton *roundedRectButton4 = [UIButton buttonWithType:UIButtonTypeRoundedRect];
  roundedRectButton4.frame = CGRectMake(10, 240, 147, 50);
  [textureView1ContentView addSubview:roundedRectButton4];
  roundedRectButton4.alpha = 1.0;
  roundedRectButton4.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [roundedRectButton4 setTitle:@"Save" forState:UIControlStateNormal];
  [roundedRectButton4 setTitleColor:[UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0] forState:UIControlStateNormal];
  roundedRectButton4.titleLabel.font = [UIFont fontWithName:@".HelveticaNeueUI-Bold" size:15.0];
  [roundedRectButton4 addTarget:self action:@selector(didTap_roundedRectButton4:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UITextField -> textField1;
  // ----------------------------;
  
  UITextField *textField1 = [[UITextField alloc] initWithFrame:CGRectMake(10, 200, 300, 31)];
  [contentView addSubview:textField1];
  textField1.alpha = 1.0;
  textField1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField1.text = @"Species";
  textField1.borderStyle = UITextBorderStyleRoundedRect;
  textField1.textAlignment = UITextAlignmentLeft;
  textField1.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField1.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField1.font = [UIFont fontWithName:@".HelveticaNeueUI" size:17.0];
  [textField1 release];
  
  
  // ----------------------------;
  // UITextField -> textField2;
  // ----------------------------;
  
  UITextField *textField2 = [[UITextField alloc] initWithFrame:CGRectMake(10, 240, 130, 31)];
  [contentView addSubview:textField2];
  textField2.alpha = 1.0;
  textField2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField2.text = @"Length";
  textField2.borderStyle = UITextBorderStyleRoundedRect;
  textField2.textAlignment = UITextAlignmentLeft;
  textField2.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField2.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField2.font = [UIFont fontWithName:@".HelveticaNeueUI" size:17.0];
  [textField2 release];
  
  
  // ----------------------------;
  // UITextField -> textField3;
  // ----------------------------;
  
  UITextField *textField3 = [[UITextField alloc] initWithFrame:CGRectMake(180, 240, 130, 31)];
  [contentView addSubview:textField3];
  textField3.alpha = 1.0;
  textField3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField3.text = @"Weight";
  textField3.borderStyle = UITextBorderStyleRoundedRect;
  textField3.textAlignment = UITextAlignmentLeft;
  textField3.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField3.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField3.font = [UIFont fontWithName:@".HelveticaNeueUI" size:17.0];
  [textField3 release];
  
  
  // ----------------------------;
  // UITextView -> textView1;
  // ----------------------------;
  
  UITextView *textView1 = [[UITextView alloc] initWithFrame:CGRectMake(10, 285, 300, 103)];
  [contentView addSubview:textView1];
  textView1.alpha = 1.0;
  textView1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textView1.text = @"Notes";
  textView1.textAlignment = UITextAlignmentLeft;
  textView1.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textView1.backgroundColor = [UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0];
  textView1.font = [UIFont fontWithName:@".HelveticaNeueUI" size:12.0];
  [textView1 release];
  
  
  contentView.frame = self.view.bounds;
  [self.view addSubview:contentView];
  [contentView release];
}

- (void)viewDidUnload {
  [super viewDidUnload];
}

- (void)dealloc {
  [super dealloc];
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationFade];
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleDefault animated:animated];
}


// ----------------
// Navigation Bar
// ----------------

- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
  return NO;
}

// ----------------
// Action
// ----------------

- (void)didTap_imageButton1:(id)sender forEvent:(UIEvent *)event {
  SettingsViewController *controller = [[SettingsViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_imageButton2:(id)sender forEvent:(UIEvent *)event {
  NewRouteViewController *controller = [[NewRouteViewController alloc] init];
  [self.navigationController pushViewController:controller animated:NO];
  [controller release];
}
- (void)didTap_roundedRectButton3:(id)sender forEvent:(UIEvent *)event {
  HomeViewController *controller = [[HomeViewController alloc] init];
  [self.navigationController pushViewController:controller animated:NO];
  [controller release];
}
- (void)didTap_roundedRectButton4:(id)sender forEvent:(UIEvent *)event {
  NewRouteViewController *controller = [[NewRouteViewController alloc] init];
  [self.navigationController pushViewController:controller animated:NO];
  [controller release];
}




@end